### ISSUE TITLE
Errors in translation

### ISSUE THREAD

**Issue by MaxAlex666** [Klucherev/ra-language-russian#1]
single_missing: 'Выюранная ссылка больше недоступна' // Опечатка
invalid_form: 'На форме обнаружены ошибки'  // Может быть лучше: 'В форме обнаружены ошибки'
email: 'Не корректный email' // Некорректный - слитно

**Comment by Klucherev** [comment]
@MaxAlex666 Согласен. Поспешил ))
Выложил новую версию https://github.com/Klucherev/ra-language-russian/commit/0548257929116d805c07abb25d57d041dc8c2cbd

**Comment by MaxAlex666** [comment]
Оперативно! Спасибо, забрал.

**Comment by MaxAlex666** [comment]
Ещё мелкое замечание - number: 'Должно быть цифрой'
Мне кажется - "Должно быть числом" более верно по смыслу? Цифра обычно если один разряд.
