### ISSUE TITLE
New untranslated messages in ra-admin

### ISSUE THREAD

**Issue by MaxAlex666** [Klucherev/ra-language-russian#2]
'ra.navigation.no_more_results'
'ra.navigation.page_rows_per_page'

**Comment by Klucherev** [comment]
Thnx!
https://github.com/Klucherev/ra-language-russian/commit/d6c1439f697c5db2014d789b7757691484d94515

**Comment by VikhorevaDarya** [comment]
'ra.configurable.customize'
